name: Deploy Client to Azure Static Web Apps (OIDC)

on:
  push:
    branches: [ main ]
    paths:
      - "Client/**"
      - ".github/workflows/azure-static-web-apps-nice-flower-04e426c10.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (Vite needs Node 20+)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: Client/package-lock.json

      - name: Install (Client)
        working-directory: Client
        run: npm ci

      - name: Build (Client)
        working-directory: Client
        run: npm run build

      - name: Get Id Token
        id: idtoken
        uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken();
            return token;
          result-encoding: string

      - name: Upload to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: Client
          app_artifact_location: dist
          skip_app_build: true
          github_id_token: ${{ steps.idtoken.outputs.result }}
