name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (Client)
        working-directory: Client
        run: npm ci

      - name: Build (Client)
        working-directory: Client
        run: npm run build

      - name: Get Id Token
        id: idtoken
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            return await core.getIDToken();
          result-encoding: string

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_FLOWER_04E426C10 }}
          app_location: "./Client"
          output_location: "dist"
          skip_app_build: true                 # <- we already built
          github_id_token: ${{ steps.idtoken.outputs.result }}
